# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: https://YUROUROU1998.github.io # the base hostname & protocol for your site, e.g. http://example.com
baseurl: /MabelsProfile.github.io # the subpath of your site, e.g. /blog
title: Mabel's Profiles
description: "HI WELCOME TO MY PERSONAL WEBSITE."
keywords: 'jekyll, personal blog, profiles'
author:
  name: 余柔柔 Mabel
  job_title: Student
  location: Taipei, Taiwan
  email: bcctshiyurourou@gmail.com
  social_links:
    - name: facebook
      url: https://www.facebook.com/bcctshirou/
    - name: github
      url: https://github.com/YUROUROU1998/MabelsProfile.github.io
    - name: instagram
      url: https://www.instagram.com/youyor37/
    - name: linkedin
      url: https://www.linkedin.com/in/mabelrryu/

home:
  section1: <h1>Welcome to my blog</h1>
  section2: <h2>Sharing my thoughts on tech and life</h2>
  section3: <div class="social-links"><a class="ico-github btn" href="https://yurourou1998.github.io/mabel_website.github.io/" title="Map, Foods, Smiles"></a></div>
blog:
  cc_license: http://creativecommons.org/licenses/by-sa/4.0/ # A link to CC License of your choice.
  cc_license_image: /assets/images/theme/cc-by-sa.png # An image of your CC License. 
  footer_content: A gem-based responsive simple texture styled <a href="http://jekyllrb.com/">Jekyll</a> theme.

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
